### ISSUE TITLE
SharedPosts field not returning anything

### ISSUE THREAD

**Issue by ahmedhawas** [nov/fb_graph#343]
I am trying to to fetch for a certain post who shared it. On the Facebook Graph API I am able to fetch that data through the field sharedposts:  (graph.facebook.com/POST_ID?fields=sharedposts) 

However I tried adding that field using the gem, but it doesnt seem to work and doesn't return anything. Does the gem support that? 

Thanks

**Comment by avokhmin** [comment]
+1
https://developers.facebook.com/docs/graph-api/reference/v2.3/post#edges
