### ISSUE TITLE
FbGraph::InvalidRequest on FbGraph::Page.fetch

### ISSUE THREAD

**Issue by brunocavalcante** [nov/fb_graph#367]
FbGraph::Page.fetch(foo) is throwing a GraphMethodException. Full message: "GraphMethodException :: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api".

Perhaps a side effect of some API change on Facebook?

**Comment by dgp** [comment]
Facing same error when i fetch page detail by page id. Works partially.
For eg: 
  1. FbGraph::Page.fetch('245774372153') - can't access this page
  But that page exist here is the url - https://www.facebook.com/pages/Urban-Curry/245774372153
  2. FbGraph::Page.fetch('142157902556944') - can access this page.
