### ISSUE TITLE
Access custom fields for posts

### ISSUE THREAD

**Issue by nishantbeans** [nov/fb_graph#384]
Is there a possibility to fetch custom fields from page  `posts?fields=full_picture,`

```ruby
   app = FbGraph::Application.new(facebook_app_id, :secret => facebook_secret_key)
   access_token = app.get_access_token
   page = FbGraph::Page.new(page_id, :access_token => access_token)
   posts = page.posts
``` 
I am trying to fetch results similar to https://graph.facebook.com/page_id/posts?fields=full_picture&access_token=access_token
```js
"data": [
      {
         "full_picture": "https://m.ak.fbcdn.net/xyz.jpg",
         "link": "http://xyz.com",
         "id": "123456_123456",
         "created_time": "2014-12-30T09:00:48+0000"
      }
``` 
I read about events but that doesn't seems to work. I am basically trying to fetch the bigger picture with post

**Comment by nov** [comment]
`FbGraph::Node#raw_attributes` is for such purpose.
https://github.com/nov/fb_graph/blob/master/lib/fb_graph/node.rb#L13

**Comment by nishantbeans** [comment]
![screenshot at 2015-01-05 12 29 15](https://cloud.githubusercontent.com/assets/3529906/5610113/8bbcc852-94d6-11e4-94a9-182e3b8e1667.png)

Am I missing something? Custom fields such as full_picture should be part of post?

**Comment by nov** [comment]
if the post has the attribute, it should be included in its `raw_attributes` hash.
