### ISSUE TITLE
refresh token - if user change password

### ISSUE THREAD

**Issue by ikaiser** [nov/fb_graph#385]
Hy Everyone!
When a user changes his password token is regenerated, and my app can not longer use that token, to make calls to Facebook API, how can I automatically regenerate the token ??
thanks.

**Comment by nov** [comment]
you can't.
ask the user to re-login.

**Comment by ikaiser** [comment]
there is no other solution ??

**Comment by nov** [comment]
once the access token is revoked/expired, you have no chance to regenerate new one without user interaction.

**Comment by ikaiser** [comment]
Normally how tough a token ??

**Comment by nov** [comment]
If you got it via OAuth2 token endpoint, its lifetime should be 60 days.
ref.) https://developers.facebook.com/docs/facebook-login/access-tokens#extending

**Comment by ikaiser** [comment]
and I can make that at 59 days in the user's token automatically regenerate ??

**Comment by nov** [comment]
sorry, I can't understand your english..

**Comment by ikaiser** [comment]
59 th day can automatically regenerate the token?

**Comment by nov** [comment]
Ah, i see.
You can't extend token lifetime more than 60 days, so you have to ask users to re-login at least each 60 days.

Using FB iOS/Android SDK, the token lifetime rule might be different though.

**Comment by ikaiser** [comment]
thanks a lot for everything :)

**Comment by nov** [comment]
np
