### ISSUE TITLE
Sync User with Streaming Facebook - limit call FB Api

### ISSUE THREAD

**Issue by ikaiser** [nov/fb_graph#386]
Hy Everyone,
i have an question, I would like to synchronize streaming of my users.
Some of my users, have had to regenerate the password, because facebook warned them they were using an app very similar to facebook could be because I do too many calls to the Facebook API ??

**Comment by nov** [comment]
You should ask such kind of questions for FB developer support team.
I don't know how FB detects spammy apps.

**Comment by ikaiser** [comment]
ok thanks.
