### ISSUE TITLE
Notifications don't work

### ISSUE THREAD

**Issue by ikaiser** [nov/fb_graph#387]
I have this code:

#fb_user is my facebook user

fb_user = FbGraph::User.fetch(auth.uid, {:access_token => auth.token, :locale => @user.language})
fb_user.notification!(
  :access_token => APP_ACCESS_TOKEN,
  :href => 'http://matake.jp',
  :template => 'Your friend @[12345] achieved new badge!'
)

but dont notify me

**Comment by nov** [comment]
If it returns `true` but you don't get the notification, ask FB.
