### ISSUE TITLE
How about batch requests?

### ISSUE THREAD

**Issue by gazay** [nov/fb_graph#389]
Hello! Is there a way to use power of [batch requests](https://developers.facebook.com/docs/graph-api/making-multiple-requests) with fb_graph?

Thank you for awesome gem!

**Comment by nov** [comment]
No, this gem don't support batch requests.

**Comment by gazay** [comment]
I would like to try add batches support to this gem. I just use this gem a lot in my current project and I think it is a perfect place where this functional should be :)

**Comment by nov** [comment]
let me close this unactive issue.
