### ISSUE TITLE
how to get all friends of a user

### ISSUE THREAD

**Issue by MohammedShehata** [nov/fb_graph#393]
user = FbGraph2::User.new('user_id').authenticate('access_token')
user = user.fetch

user.friends   # get only one or two users not all the users

**Comment by nov** [comment]
You can't do that because FB closed the feature.

**Comment by MohammedShehata** [comment]
thanks for reply

**Comment by MohammedShehata** [comment]
Is there any alternatives I can use to be able to invite the user's friends to use my app ??
